# Generated by Django 4.1 on 2022-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daycalendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar", name="data", field=models.DateTimeField(),
        ),
    ]
